### ISSUE TITLE
Question about the concept

### ISSUE THREAD

**Issue by rjjrbatarao** [sepfy/pear-esp32-examples#2]
Amazing Im excited to try!! Thank you for providing an example for esp32 cam :), I'm new to p2p concepts and I want to know if I get how your code works.
ESP32 and the sample html connects to stun server and receive information about its nat
ESP32 and the sample html exchanges those nat information through the public mqtt broker
Then finally initiate its peer connection using the nat information through the protocol handled by your srtp library.

Some questions:
does your library handle multiple alternate stun/turn servers and how to customize it to my stun servers?
can you open multiple datachannel like 1 binary video and 1 json data channel at thesame time?
do you have porting guides to Arduino or PlatformIO IDE, maybe this will be my assignment :)

**Comment by sepfy** [comment]
Hello~
Yes~ About nat information and exchanging, you are right. SRTP is used to encrypt the media data. in this example, 
i haven't used it yet. It will be used for streaming audio data. For now, it streams JPEG by datachannel (SCTP), because JPEG is not a media data type in the WebRTC specification.

1. If you want to customized stun server, you can modify pear library. it not supports multiple stun/turn servers
https://github.com/sepfy/pear/blob/esp32/src/agent.h#L19
2. Currently does not support multiple datachannels, but you can try to send data with ```peer_connection_datachannel_send_binary``` and ```peer_connection_datachannel_send``` to identify binary and text
3. Sorry. i am not familiar with Arduino or PlatformIO IDE. I have no experience with porting to IDE

So far ESP32 has been able to successfully establish a P2P connection, but there are still many protocol that have not been completed. I may complete the stable transmission of Microphone and Camera data first. Then implement other functions, such as support for multiple stun/turn servers, etc.

**Comment by rjjrbatarao** [comment]
Wow thank you so much, looking forward to this
